### ISSUE TITLE
Will this be published ?

### ISSUE THREAD

**Issue by dandxy89** [milenkovicm/testcontainers-redpanda-rs#12]
Hi @milenkovicm,

Thanks for working on this project I've been experimenting with a number of projects at Sigma. Do you intend to publish this on Crates.io at all?

**Comment by milenkovicm** [comment]
Hi @dandxy89,
thanks for reaching out! 
I can publish it, no problem. 
Did you try to use it? Any improvement suggestions ?

**Comment by dandxy89** [comment]
Yes I have used it in 4 services now and it has been very reliable and currently does all that I need (init, create X topics and shutdown).

If I were to offer some suggestions.

1. It would be nice to be able to pass custom RPK configuration that such that I can align it with the clusters I have running but at this time its more of a nice-to-have than a feature request. Config that users _may_ want to change might include:

```
default_topic_partitions: X
default_topic_replications: Y
auto_create_topics_enabled: true
kafka_batch_max_bytes: Z
```

2. And then for debugging being able to connect or init the Admin UI could be useful.

**Comment by milenkovicm** [comment]
All right, let me try to publish crate first

**Comment by milenkovicm** [comment]
reopening this issue, will close it once I publish it

**Comment by milenkovicm** [comment]
https://crates.io/crates/testcontainers-redpanda-rs give it a try @dandxy89 when you get chance

**Comment by dandxy89** [comment]
I will take a look today. 

Congratulations on the first release. I'm sure others will be grateful for your time in setting this up.
